---
title: "Practica de dplyr"
author: "Jenny Gonzalez Masis"
format: html
toc: true
lang : es
theme: morph
---

# Introduccion 
Este documento presenta ejemplos de uso de las funciones del paquete dplyr 

# Carga de paquetes

```{r}
#| label: carga-paquetes 
#| message: false
#| warning: false

library(tidyverse)
library(knitr)
library(palmerpenguins)
```

# Carga de datos

```{r}
#| label: carga-datos
#| #| message: false
#| warning: false


delitos <- read_csv("estadisticaspoliciales2023.csv")
```

# select()

# Ejemplo 1

```{r}
#| label: select-01

# kable(penguins)

penguins |>
  select(species, sex, year) |>
  kable()
```

# Ejemplo 2

```{r}
#| label: select-02

# Cambio de nombre de columnas
penguins |>
  select(
    especie = species,
    sexo = sex, 
    año = year 
  ) |>
  kable()
```

# filter() 

## Ejemplo 1

```{r}
#| label: filter-01

# Pinguinos de la especie Adelie y que son machos y que habitan la isla Biscoe
penguins |>
  filter(species == "Adelie" & sex == "male" & island == "Biscoe") |> 
  kable()
```

## Ejemplo 2

```{r}
#| label: filter-02

# Pinguinos que viven en la isla Biscoe o en la isla Torgersen

penguins |> 
  filter(island == "Biscoe" | island == "Torgersen") |>
  kable()
```

## Ejemplo 3

```{r}
#| label: filter-03

# Robos cometidos en San Pedro de Montes de Oca 

delitos |> 
  filter(Delito == "ROBO" & Canton == "MONTES DE OCA" & Distrito == "SAN PEDRO") |> 
  select(Delito, SubDelito, Victima, SubVictima, Canton, Distrito) |> 
  kable()
```

## Ejemplo 4

```{r}
#|label: filter-04

# Pinguinos con NA en la columna de sexo
penguins |>
  filter(is.na(sex)) |>
  kable()
```





# arrange() 

##Ejemplo 1

```{r}
#| label: arrange-01

delitos |>
  filter(Delito == "ROBO DE VEHICULO" & Canton == "MONTES DE OCA") |> 
  select(Delito, SubDelito, Hora, Canton, Distrito) |>
arrange(Distrito, Hora) |>
kable()
```

##Ejemplo 2

```{r}
#| label: arrange-02

penguins |>
  arrange(desc(body_mass_g)) |>
 kable()
```

# mutate()

## Ejemplo 1 

```{r}
#| label: mutate-01

penguins |>
select(species, body_mass_g) |>
  mutate(body_mass_kg = body_mass_g/1000)
```

## Ejemplo 2

```{r}
#| label: mutate-02

delitos |> 
   mutate(Fecha_Date = as.Date(delitos$Fecha, format="%m/%d/%Y")) |>
  filter(Canton == "MONTES DE OCA") |>
  select(Fecha_Date, Canton, Delito, SubDelito) |>
  arrange(Fecha_Date) |>
  kable()
```

# summarize() 

## Ejemplo 1 

```{r}
#| label: summarize-01

penguins |>
  group_by(species) |>
  summarize(
    body_mass_g_min = min(body_mass_g, na.rm = TRUE),
    body_mass_g_max = max(body_mass_g, na.rm = TRUE),
    body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
    n = n()
  )
```

## Ejemplo 2

```{r}
#| label: summarize-02

# Cantidad de homicidios por provincia y cantón
delitos |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Provincia, Canton) |>
  summarize(
    homicidios_2023 = n()
  ) |>
  arrange(desc(homicidios_2023)) |>
  kable()


```

## Ejemplo 3

```{r}
#| label: summarize-03

# Cantidad de homicidios por genero
delitos |>
  filter(Delito == "HOMICIDIO") |>
  group_by(Genero) |>
  summarize(
    homicidios_2023 = n()
  ) |>
  arrange(desc(homicidios_2023)) |>
  kable()
```

## Ejemplo 4

```{r}
#| label: summarize-04

# Cantidad de asaltos por edad
delitos |>
  filter(Delito == "ASALTO") |>
  group_by(Edad) |>
  summarize(
    asalto_2023 = n()
  ) |>
  arrange(desc(asalto_2023)) |>
  kable()
```

## Ejemplo 5


```{r}
#| label: summarize-05


# Promedio de masa y n cantidad de registros de pingüinos
penguins |>
  summarise(body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
            n = n())
```

## Ejemplo 6

```{r}
#| label: summarize-06

penguins |>
  summarise(body_mass_g_mean = mean(body_mass_g, na.rm = TRUE),
           body_mass_g_min = min(body_mass_g, na.rm = TRUE),
            body_mass_g_max = max(body_mass_g, na.rm = TRUE),
            n = n())
```












